### PR TITLE
Fix crash on unknown variable

### LINKED ISSUE #2: Silent crash on encountering undefined variable

### PR DESCRIPTION
**Pull request by TarCV**
Fix #2

### CODE REVIEW

**Comment by ghost** [comment]
Using https://github.com/TarCV/debotc/blob/master/debotc_defs.bts as botc_defs.bts and mentioning an undeclared $global6 variable anywhere in the source:
```
Parsing script...
Declared global variable #0 $global0
Declared global variable #1 $global2
Declared global variable #2 $global3
Declared global variable #3 $global4
Declared global variable #4 $global5
Declared global variable #5 $globalArray1
error: crashbot.botc:14:11: unknown variable $global6
```
It works as intended.

**Comment by TarCV** [comment]
Thank you. Merged.

Does botc_defs from this repository work for you? The one from debotc repo is good for debugging as it allows compiling sources produced by debotc, but it might lack some fixes or updates.

**Comment by ghost** [comment]
It doesn't work when compiling the decompiled crashbot source, that is why I used the debotc one.

**Comment by ghost** [comment]
```
Parsing script...
Declared global variable #0 $global0
Declared global variable #1 $global2
Declared global variable #2 $global3
Declared global variable #3 $global4
Declared global variable #4 $global5
Declared global variable #5 $globalArray1
error: crashbot.botc:27:20: IsSpectating returns an incompatible data type
```

**Pull request merged**
